force-app/main/default/objects/Account/fields/BH_Collection_Name__c.field-meta.xml
<CustomField>
    <fullName>BH_Collection_Name__c</fullName>
    <description>BH_Collection_Name</description>
    <label>BH Collection Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collection_Item__c/Collection_Item__c.object-meta.xml
<CustomObject>
    <label>Collection Item</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Collection Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Item__c/fields/Company_Collection__c.field-meta.xml
<CustomField>
    <fullName>Company_Collection__c</fullName>
    <label>Company Collection</label>
    <referenceTo>Company_Collection__c</referenceTo>
    <relationshipLabel>Collection Items</relationshipLabel>
    <relationshipName>Collection_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Collection_Item__c/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company ID</label>
    <referenceTo>Company_ID__c</referenceTo>
    <relationshipLabel>Collection Items</relationshipLabel>
    <relationshipName>Collection_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Collection__c/Company_Collection__c.object-meta.xml
<CustomObject>
    <label>Company Collection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Company Collection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company_Collection__c/fields/beauhurst_id__c.field-meta.xml
<CustomField>
    <fullName>beauhurst_id__c</fullName>
    <externalId>true</externalId>
    <label>beauhurst id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Company_Collection__c/fields/collection_name__c.field-meta.xml
<CustomField>
    <fullName>collection_name__c</fullName>
    <label>collection name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_ID__c/Company_ID__c.object-meta.xml
<CustomObject>
    <label>Company ID</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Company ID	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateAccountsFromBHBatch.cls
global class CreateAccountsFromBHBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    global Set<String> ids;
    
    global CreateAccountsFromBHBatch(){
        this.ids = new Set<String>();
    }

    global CreateAccountsFromBHBatch(Set<String> ids){
        this.ids = ids;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Name, beauhurst_id__c';
        query += ' FROM Company_ID__c';
        query += ' WHERE beauhurst_id__c != null';
        if(!ids.isEmpty()){
            query += ' AND beauhurst_id__c IN: ids';
        }
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Company_ID__c> scope){
        Set<Id> companyRecordIds = new Set<Id>();
        String companyIds = '';
        Map<String, String> beauhurstIdToCollectionNameMap = new Map<String, String>();
        for(Company_ID__c ci : scope){
            companyRecordIds.add(ci.Id);
            companyIds += 'company_ids=' + ci.beauhurst_id__c + '&';
        }

        if(!companyRecordIds.isEmpty()){
            for(Collection_Item__c cItem : [SELECT Id, Company_ID__r.beauhurst_id__c, Company_Collection__r.collection_name__c FROM Collection_Item__c WHERE Company_ID__c IN: companyRecordIds]){
                beauhurstIdToCollectionNameMap.put(cItem.Company_ID__r.beauhurst_id__c, cItem.Company_Collection__r.collection_name__c);
            }
        }

        String append = '/companies?' + companyIds + 'includes=registered_name&includes=other_trading_names&includes=website&includes=ultimate_parent_company&includes=top_level_industry_groups&includes=top_level_sector_groups&includes=buzzwords&includes=latest_stage_of_evolution&includes=legal_form&includes=year_end_date&includes=turnover&includes=ebitda&includes=total_assets&includes=number_of_employees&includes=auditor&includes=audit_fees&includes=emails&includes=directors';

        Http http = new Http();
        HttpResponse res = http.send(BeauhurstAPIUtility.constructReq(append));
        if(res.getStatusCode() == 200){
            BeauhurstAPIUtility.Response getData = (BeauhurstAPIUtility.Response) JSON.deserialize(res.getBody(), BeauhurstAPIUtility.Response.class);
            if(!getData.results.isEmpty()){
                List<User> users = [SELECT Id FROM User WHERE Name = 'Sal Mingoia' AND isActive = true LIMIT 1];
                if(!users.isEmpty()){
                    List<Account> accountsToInsert = new List<Account>();
                    for(BeauhurstAPIUtility.Result result : getData.results){
                        Account acc = BeauhurstAPIUtility.collectAccount(null, result);
                        acc.Type = 'Target';
                        if(beauhurstIdToCollectionNameMap.containsKey(result.id)){
                            acc.BH_Collection_Name__c = beauhurstIdToCollectionNameMap.get(result.id);
                        }
                        acc.RecordTypeId = BeauhurstAPIUtility.getRecordTypeIdbyName('Account', 'Business Account');
                        acc.OwnerId = users[0].Id;
                        accountsToInsert.add(acc);
                    }
    
                    if(!accountsToInsert.isEmpty()){
                        Database.SaveResult[] results = Database.insert(accountsToInsert, false);
                    }
                }
            }
        }
    }

    global void finish(Database.BatchableContext BC){
        
    }

    public class Response{
        public List<Result> results;
    }

    public class Result{
        public String id;
        public Basic basic;
        public Accounts latest_accounts;
        public List<Accounts> historic_accounts;
    }

    public class Basic{
        public String companies_house_id;
        public String employee_count_range;
    }

    public class Accounts{
        public Integer turnover;
        public Integer ebitda;
        public Integer total_assets;
    }
}