force-app/main/default/objects/Sharepoint_API__c/Sharepoint_API__c.object-meta.xml
<CustomObject>
    <label>Sharepoint API</label>
    <nameField>
        <displayFormat>SA-{000}</displayFormat>
        <label>Sharepoint API Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sharepoint API</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sharepoint_API__c/fields/access_token__c.field-meta.xml
<CustomField>
    <fullName>access_token__c</fullName>
    <label>access_token</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sharepoint_Setting__c/Sharepoint_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Sharepoint Setting</label>
</CustomObject>

force-app/main/default/objects/Sharepoint_Setting__c/fields/drive_id__c.field-meta.xml
<CustomField>
    <fullName>drive_id__c</fullName>
    <label>drive_id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sharepoint_Setting__c/fields/tenant_identifier__c.field-meta.xml
<CustomField>
    <fullName>tenant_identifier__c</fullName>
    <label>tenant_identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandlerTest.cls
@isTest
private class CaseTriggerHandlerTest {
    @TestSetup
    static void makeData(){
        Sharepoint_Setting__c sett = new Sharepoint_Setting__c();
        sett.tenant_identifier__c = '123';
        sett.client_id__c = '1234';
        sett.client_secret__c = '1rdedw';
        sett.drive_id__c = '12323';
        insert sett;

        Sharepoint_API__c api = new Sharepoint_API__c();
        api.access_token__c = '123';
        insert api;
    }

    @isTest
    static void onCaseInsert(){
        QueueHttpMock mock = new QueueHttpMock();

        HttpResponse newFolderError = new HttpResponse();
        newFolderError.setStatusCode(401);
        newFolderError.setBody('{"message": "sample"}');
        mock.addResponse(newFolderError);

        HttpResponse getToken = new HttpResponse();
        getToken.setStatusCode(200);
        getToken.setBody('{"access_token": "1234343"}');
        mock.addResponse(getToken);

        HttpResponse newFolderOK = new HttpResponse();
        newFolderOK.setStatusCode(200);
        newFolderOK.setBody('{"id": "65454534"}');
        mock.addResponse(newFolderOK);

        HttpResponse publicFolder = new HttpResponse();
        publicFolder.setStatusCode(200);
        publicFolder.setBody('{"id": "65454534", "webUrl": "https://test.sharepoint.com/sites/rfdfdf"}');
        mock.addResponse(publicFolder);

        HttpResponse secureFolder = new HttpResponse();
        secureFolder.setStatusCode(200);
        secureFolder.setBody('{"id": "3434343", "webUrl": "https://test.sharepoint.com/sites/fdjdfksd"}');
        mock.addResponse(secureFolder);

        Test.setMock(HttpCalloutMock.class, mock);

        Test.startTest();
            Case cas = new Case();
            cas.Subject = 'Test';
            insert cas;
        Test.stopTest();
    }


}