force-app/main/default/objects/Collection_Item__c/Collection_Item__c.object-meta.xml
<CustomObject>
    <label>Collection Item</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Collection Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Item__c/fields/Company_Collection__c.field-meta.xml
<CustomField>
    <fullName>Company_Collection__c</fullName>
    <label>Company Collection</label>
    <referenceTo>Company_Collection__c</referenceTo>
    <relationshipLabel>Collection Items</relationshipLabel>
    <relationshipName>Collection_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Collection_Item__c/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company ID</label>
    <referenceTo>Company_ID__c</referenceTo>
    <relationshipLabel>Collection Items</relationshipLabel>
    <relationshipName>Collection_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Item__c/fields/Item_Key__c.field-meta.xml
<CustomField>
    <fullName>Item_Key__c</fullName>
    <externalId>true</externalId>
    <label>Item Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Company_Collection__c/Company_Collection__c.object-meta.xml
<CustomObject>
    <label>Company Collection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Company Collection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company_Collection__c/fields/beauhurst_id__c.field-meta.xml
<CustomField>
    <fullName>beauhurst_id__c</fullName>
    <externalId>true</externalId>
    <label>beauhurst id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Company_Collection__c/fields/collection_name__c.field-meta.xml
<CustomField>
    <fullName>collection_name__c</fullName>
    <label>collection name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Collection__c/fields/sync__c.field-meta.xml
<CustomField>
    <fullName>sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Company_ID__c/Company_ID__c.object-meta.xml
<CustomObject>
    <label>Company ID</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Company ID	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GetCompanyIdBatch.cls
global class GetCompanyIdBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful, Database.AllowsCallouts {
    global Set<Id> collectionIds;
    global Set<String> validCompanyIds;

    global void execute(SchedulableContext SC) {
        Database.executebatch(new GetCompanyIdBatch(), 1); 
    }

    //Database.executeBatch(new GetCompanyIdBatch(), 1);
    global GetCompanyIdBatch(){
        this.collectionIds = new Set<Id>();
        this.validCompanyIds = new Set<String>();
    }

    global GetCompanyIdBatch(Set<Id> collectionIds){
        this.collectionIds = collectionIds;
        this.validCompanyIds = validCompanyIds;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Name, beauhurst_id__c, collection_name__c';
        query += ' FROM Company_Collection__c';
        query += ' WHERE beauhurst_id__c != null';
        query += ' AND sync__c = true';
        if(!collectionIds.isEmpty()){
            query += ' AND Id IN: collectionIds';
        }
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Company_Collection__c> scope){
        Set<String> retrievedCompanyIds = new Set<String>();
        Integer offsetVal = 0;
        Integer limitVal = 100;
        Boolean isLoop = true;

        while(isLoop){
            String append = '/companies/search?collection_id=' + scope[0].beauhurst_id__c + '&limit=' + limitVal + '&offset=' + offsetVal;

            Http http = new Http();
            HttpResponse res = http.send(BeauhurstAPIUtility.constructReq(append));
            if(res.getStatusCode() == 200){
                Response getData = (Response) JSON.deserialize(res.getBody(), Response.class);
                if(!getData.results.isEmpty()){
                    offsetVal += 100;
                    for(Result result : getData.results){
                        retrievedCompanyIds.add(result.id);
                    }
                }else{
                    isLoop = false;
                }
            }else{
                isLoop = false;
            }
        }

        if(!retrievedCompanyIds.isEmpty()){
            List<Company_ID__c> companyIdsToUpsert = new List<Company_ID__c>();
            Map<String, Account> bhIdToAccountMap = new Map<String, Account>();

            for(Account acc : [SELECT Id, Beauhurst_ID__c FROM Account WHERE Beauhurst_ID__c IN: retrievedCompanyIds]){
                bhIdToAccountMap.put(acc.Beauhurst_ID__c, acc);
            }

            for(String compId : retrievedCompanyIds){
                if(!bhIdToAccountMap.containsKey(compId)){
                    Company_ID__c comId = new Company_ID__c();
                    comId.beauhurst_id__c = compId;
                    companyIdsToUpsert.add(comId);
                }
            }

            if(!companyIdsToUpsert.isEmpty()){
                Schema.SObjectField extId = Company_ID__c.Fields.beauhurst_id__c;
                Database.UpsertResult[] results = Database.upsert(companyIdsToUpsert, extId, false);
    
                List<Collection_Item__c> collectionItemsToUpsert = new List<Collection_Item__c>();
                for(Integer index = 0, size = results.size(); index < size; index++) {
                    if(results[index].isSuccess()){
                        validCompanyIds.add(companyIdsToUpsert.get(index).beauhurst_id__c);
                        if(results[index].isCreated()){
                            Collection_Item__c itm = new Collection_Item__c();
                            itm.Company_Collection__c = scope[0].Id;
                            itm.Company_ID__c = results[index].getId();
                            itm.Item_Key__c = scope[0].beauhurst_id__c + '-' + companyIdsToUpsert.get(index).beauhurst_id__c;
                            collectionItemsToUpsert.add(itm);
                        }
                    }
                }
    
                if(!collectionItemsToUpsert.isEmpty()){
                    upsert collectionItemsToUpsert Item_Key__c;
                }
            }
        }
    }

    global void finish(Database.BatchableContext BC){
        System.debug('@@@validCompanyIds: ' + validCompanyIds);
        Database.executeBatch(new CreateAccountsFromBHBatch(validCompanyIds), 10);
    }

    public class Response{
        public List<Result> results;
    }

    public class Result{
        public String id;
    }
}